<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Highschool Graduates</name>
   <tag></tag>
   <elementGuidId>6867a5b1-4181-423b-8bb4-f33485dccddc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='abfbe4ffd823-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#abfbe4ffd823-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3208513a-f24d-40be-85bb-774028ff95e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-option-marked</value>
      <webElementGuid>fabe65d8-77f2-4f53-b241-3d76d930e235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>efa4a6d2-c66e-4c3c-98d2-ef268adfe1b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b0573185-8b34-4b37-9003-c18ede0319ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>abfbe4ffd823-2</value>
      <webElementGuid>404c383c-b2bf-41c6-939a-a1fcc82daf27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Highschool Graduates</value>
      <webElementGuid>4432a3d6-1678-439f-bb87-c74c562b5760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;abfbe4ffd823-2&quot;)</value>
      <webElementGuid>97faecd0-37c6-4f8b-af53-c7aab663b54e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='abfbe4ffd823-2']</value>
      <webElementGuid>adb16b4d-6d18-46f2-b02f-d3d1aca10fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='abfbe4ffd823']/div/div[2]/div[3]</value>
      <webElementGuid>9fdf77ed-11bc-48d5-bd40-63e3363a6f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='College Graduates'])[2]/following::div[1]</value>
      <webElementGuid>51d7f41e-6654-4569-972a-79451275f8fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='College'])[1]/following::div[2]</value>
      <webElementGuid>11787b46-ca8b-4263-b9d5-4da4acd317ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div[3]</value>
      <webElementGuid>fb8ac011-27be-4b2b-a21a-cfc23eff8e38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'abfbe4ffd823-2' and (text() = 'Highschool Graduates' or . = 'Highschool Graduates')]</value>
      <webElementGuid>4d96fc9a-b5a1-4aad-8da4-d1da9ab71dd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
