<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_College Graduates_1</name>
   <tag></tag>
   <elementGuidId>37cb073e-471b-4f82-a9bc-75735a0b8278</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='aa3c07222361-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#aa3c07222361-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>22208f62-d7de-4c4a-8e35-9b0f4e446e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-option-marked</value>
      <webElementGuid>6b4e54d4-c7a3-4a0f-a2fb-1cb6ca3c6b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>375e872e-1cba-4179-9a00-2fde203bb747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>518520a4-5700-42e4-a6e2-1fab62f18d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aa3c07222361-1</value>
      <webElementGuid>8ff29d0b-464b-4ae9-a974-ad85009b4bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>College Graduates</value>
      <webElementGuid>e9ceec80-faab-4dcf-8af9-74eec29a5ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aa3c07222361-1&quot;)</value>
      <webElementGuid>02ec5011-890f-496c-b557-e38a2091d34f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='aa3c07222361-1']</value>
      <webElementGuid>552cfd63-a263-4887-8ecf-b78c59474a4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='aa3c07222361']/div/div[2]/div[2]</value>
      <webElementGuid>ffa45b0c-a8e9-49cf-9605-6cde68a1f8fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='College'])[1]/following::div[1]</value>
      <webElementGuid>d362377e-0eae-4414-9420-ae3cea93ba1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Highschool Graduates'])[1]/preceding::div[1]</value>
      <webElementGuid>d6da0404-43e4-408f-84b3-f90d1fcf3487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div[2]</value>
      <webElementGuid>35e9b839-e860-42e7-b0ec-bc8c7554ed2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'aa3c07222361-1' and (text() = 'College Graduates' or . = 'College Graduates')]</value>
      <webElementGuid>a9ae5047-1783-4caa-b37c-efeb3d4e4557</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
