<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select Education</name>
   <tag></tag>
   <elementGuidId>322f8c69-2772-45d1-a797-a00380b7ee68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ng-select[@id='education']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ng-select-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d06d49ba-3b77-4258-948d-f57d3caa5c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-select-container</value>
      <webElementGuid>34c4408a-d438-49f1-972e-f1462956ff3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Education</value>
      <webElementGuid>90f64f39-f51c-4d60-aee1-0376a1a78c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;education&quot;)/div[@class=&quot;ng-select-container&quot;]</value>
      <webElementGuid>922eb116-f16b-43c2-90a2-f47d36c9efe7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='education']/div</value>
      <webElementGuid>e765a338-67d8-4d6f-b62f-badec5ba9a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Education'])[1]/following::div[1]</value>
      <webElementGuid>9fa5af62-0c75-4e87-b98c-910f3aac6898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::div[4]</value>
      <webElementGuid>5a588735-f8e0-4b42-ae5f-35495537ea1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/preceding::div[4]</value>
      <webElementGuid>04511c71-9eaa-4883-a814-76f6978db50e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-select/div</value>
      <webElementGuid>9b733934-1f2c-4c68-8c46-489abb4d5017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select Education' or . = 'Select Education')]</value>
      <webElementGuid>7dcdf31a-006e-4450-84d3-f7fd40dcefbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
